name: Release SDK

on:
    workflow_dispatch:
        inputs:
            dryRun:
                description: 'Do a dry run to preview instead of a real release'
                required: true
                default: 'true'

jobs:
    confirm-master-branch:
        name: Confirm release is run from master branch
        runs-on: ubuntu-latest
        steps:
            - name: Git checkout
              uses: actions/checkout@v1
            - name: Branch name
              run: |
                  BRANCHNAME=${GITHUB_REF##*/}
                  echo "pulling branch name, branch name is:"
                  echo $BRANCHNAME
                  if [ $BRANCHNAME != "master" ]
                  then
                    echo "You can only run a release from the master branch, you are trying to run it from ${BRANCHNAME}"
                    exit 1
                  fi

    release:
        name: SDK Build and Release
        runs-on: ubuntu-18.04
        needs: ['confirm-master-branch']
        env:
            GIT_AUTHOR_NAME: mparticle-bot
            GIT_AUTHOR_EMAIL: developers@mparticle.com
            GIT_COMMITTER_NAME: mparticle-bot
            GIT_COMMITTER_EMAIL: developers@mparticle.com

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  token: ${{ secrets.GH_BOT_TOKEN }}

            - name: Checkout master and merge development
              run: |
                  git checkout origin/master
                  git fetch --prune --unshallow
                  git merge origin/development

            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Install dependencies
              run: npm install ci

            - name: Run tests
              run: npm run test

            - name: Release --dry-run
              if: ${{ github.event.inputs.dryRun == 'true'}}
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: npx semantic-release --dry-run

            - name: Release
              if: ${{ github.event.inputs.dryRun == 'false'}}
              env:
                  GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  npx semantic-release
            # initiate another workflow to merge development and master since checkout will only use the commit before semantic-release does anything
            # - name: Push from master to development
            #   run: |
            #     git checkout master
            #     # git log
            #     echo "-----------------"
            #     git fetch origin development
            #     git checkout development
            #     # git log
            #     echo "-----------------"
            #     git merge master
            #     git push origin HEAD:development
            #     # git config --global user.name "mParticle-bot"
            #     # git config --global user.email "developers@mparticle.com"
